change article.html and css/style.css
rntainvaider/practic pull request #2
Opened 2024-07-23 10:58 UTC by rntainvaider

До работал контент в html странице и дописал некую стилизацию сайта css.

2024-07-24 11:35 UTC, Unnamed-193 requested changes
Хорошая работа, отлично постарался. Все правки написал, жду исправлений)

2024-07-24 11:35 UTC, Unnamed-193 commented on article.html
> +    <main class="container">
Тут main не нужно было задавать class container, по заданию, нужно было весь контент внутри body то есть main и footer обернуть в тег div и задать ему class container

1) Оберните всё содержимое тега <body> в тег <div> с классом container и напишите для него следующие стили:
.container {
margin: 0 auto;
padding: 80px 0;
width: 1170px;
}
Это нужно, чтобы контент статьи расположился по центру страницы и ограничился заданной шириной.

2024-07-24 11:35 UTC, Unnamed-193 commented on article.html
> +    <footer class="gray-box container">
Тоже самое. Тут footer не нужно было задавать class container, по заданию, нужно было весь контент внутри body то есть main и footer обернуть в тег div и задать ему class container

1) Оберните всё содержимое тега <body> в тег <div> с классом container и напишите для него следующие стили:
.container {
margin: 0 auto;
padding: 80px 0;
width: 1170px;
}
Это нужно, чтобы контент статьи расположился по центру страницы и ограничился заданной шириной.

2024-07-24 11:35 UTC, Unnamed-193 commented on article.html
> +            <h3 class="title_fhree">Основные принципы работы с отступами</h3>
Зачем нужно было менять h2 на h3 и делать для него классы? не легче было оставить везде h2 и задать им один и тот же класс?

2024-07-24 11:35 UTC, Unnamed-193 commented on article.html
>          </section>
Тут желательно было содержимое тега section обернуть в тег div и задать ему класс gray-box

2024-07-24 11:35 UTC, Unnamed-193 commented on article.html
> +    </footer>
Тут желательно было содержимое тега footer обернуть в тег div и задать ему класс gray-box

2024-07-24 11:35 UTC, Unnamed-193 commented on css/style.css
> +}
Добавьте нижний отступ для серых блоков — 40px. Чтобы соблюсти правила отступов, сделайте отступ у всех блоков, кроме последнего. У последнего серого блока, который находится в footer отступ в 40px остается, хотя его быть не должно. Может попробовать использовать :last-child, чтобы обнулить отступы у последнего блока?

2024-07-24 11:35 UTC, Unnamed-193 commented on css/style.css
> +}
Тут нет смысла писать .list .list-li, только лишняя вложенность, можно оставить .list-li
вместо названия list-li, лучше использовать list-item (item и есть элемент списка)
https://tpverstak.ru/common-css-class-names/ Почитай, тут интересно
Также у последнего элемента li отступ не обнулен((

2024-07-25 11:53 UTC, rntainvaider commented on article.html
> +            <h3 class="title_fhree">Основные принципы работы с отступами</h3>
Ну я смотря на картинку видел разный размер текста, поэтому так сделал)

2024-07-25 12:00 UTC, Unnamed-193 commented on article.html
> +            <h3 class="title_fhree">Основные принципы работы с отступами</h3>
Размер текста лучше регулировать свойством font-size

2024-07-25 12:17 UTC, rntainvaider commented on article.html
> +            <h3 class="title_fhree">Основные принципы работы с отступами</h3>
А если я все h3 сделаю одинаковое название класса 
Тогда как я могу менять им font size? 
Если видно по макету сайта, что там разный размер

2024-07-25 12:27 UTC, Unnamed-193 commented on article.html
> +            <h3 class="title_fhree">Основные принципы работы с отступами</h3>
можно задать доп класс и сделать отдельную стилизацию, если требуется например 
`<h3 class="title_fhree title">Основные принципы работы с отступами</h3>`
где title будет отельный класс, по которому можно обращаться в css
В принципе можно и так оставить, так все выглядит верно

2024-07-25 12:47 UTC, Unnamed-193 approved these changes
исправления принимаю, отличная работа!

2024-07-25 12:48 UTC, merged